<?php
/**
 * @file
 * Перенос отзывов из базы приложения appotziv
 */

define('APPOZITIV_PATH', drupal_get_path('module', 'appozitiv'));

/**
 * Implements hook_cron().
 */
function appozitiv_cron() {
  appozitiv_create_otzivi(appozitiv_get_comments());
}

/**
 * Implements hook_node_delete().
 */
function appozitiv_node_delete($node) {
  // Удаляем соответсвие в базе
  if ($node->type == 'otzivi') {
    db_delete('appozitiv')
      ->condition('nid', $node->nid)
      ->execute();
  }
}

function appozitiv_get_comments() {
  // выборка значений acid, для коммнентариев,
  // уже загруженных в базу (есть соответсвие - исключаем из выборки)
  $excludes = db_select('appozitiv', 'a')
    ->fields('a')
    ->execute()
    ->fetchAll();
  $exclude_acids = array();
  foreach ($excludes as $item) {
    $exclude_acids[] = $item->acid;
  }

  // Переключаемся на базу appozitiv
  // База данных настраивается в settings.php
  db_set_active('appozitiv');
  $query = db_select('comments', 'c')
    ->fields('c')
    ->condition('type', 2)
    ->condition('visible', 1)
    ->condition('id_clinic', 1);

  if (!empty($exclude_acids)) {
    $query->condition('id', $exclude_acids, 'NOT IN');
  };
  $comments = $query->execute()->fetchAll();
  drupal_static_reset();
  db_set_active();
  return $comments;
}

function appozitiv_create_otzivi($comments) {
  foreach ($comments as $comment) {
    //Создать пользователя
//    $user_exists = db_select('users', 'u')
//      ->fields('u')
//      ->condition('mail', $new_user_values['mail'])
//      ->execute()
//      ->fetchAll();
    $user_exists = user_load_by_mail($comment->mail);
    if ($user_exists) {
      watchdog('appozitiv', 'Пользователь @name, c электропочтой @mail существет - не создаем',
        array(
          '@name' => $user_exists['0']->name,
          '@mail' => $user_exists['0']->mail
        )
      );
      $user = $user_exists['0'];
    } else {
      $new_user_values = array(
        'name' => $comment->name,
        'mail' => $comment->mail,
        'pass' => 'pHa7-wumaDre',
        'access' => 0,
        'status' => 0
      );
      watchdog('appozitiv', 'Пользователь @name, c электропочтой @mail не существет - создаем',
        array(
          '@name' => $new_user_values['name'],
          '@mail' => $new_user_values['mail']
        )
      );
      $user = user_save($new_user_values);
    }

    //Создать ноду
    $uid = $user->uid;
    $values = array(
      'type' => 'otzivi',
      'uid' => $uid,
      'status' => 1,
      'comment' => 0,
      'promote' => 0
    );
    $entity = entity_create('node', $values);
    $ewrapper = entity_metadata_wrapper('node', $entity);
    $ewrapper->title->set('Отзыв от ' . $user->name);
    $ewrapper->body->set(array('value' => $comment->text));
    $date = new DateTime($comment->date);
    $entity->date = $comment->date;
    $entity->created = $date->getTimestamp();
    $ewrapper->save();

    // записать соответсвие в базу
    $id = db_insert('appozitiv')
      ->fields(array(
        'acid' => $comment->id,
        'nid' => $entity->nid,
      ))
      ->execute();
  }
}


/**
 * Implements hook_webform_submission_insert().
 *
 */
function appozitiv_webform_submission_insert($node, $submission) {
  $visable = 0;
  watchdog('app', '<pre>' . print_r( $submission, true) . '</pre>');
  if ($submission->nid != '56026') {
    return;
  }
  db_set_active('appozitiv');
  $id = db_insert('comments')
    ->fields(array(
      'id_clinic' => 1, //TODO указать текущий домен
      'name' => $submission->data[1][0],
      'mail' => $submission->data[2][0],
      'text' => $submission->data[3][0],
      'date' => date("Y-m-d H:i:s"),
      'type' => 1,
      'visible' => $visable,
    ))
    ->execute();

  drupal_static_reset();
  db_set_active();
  if ($id > 0) {
    watchdog('appozitiv', 'Создана запись в базе отзывов за №@id',
      array(
        '@id' => $id,
      )
    );
    if ($visable != 0) {
      appozitiv_create_otzivi(appozitiv_get_comments());
    }
  } else {
    watchdog('appozitiv', 'Не удалось создать запись с отзывами');
  }


}